name: flutter_mapbox_navigation
description: >
  Add Turn By Turn Navigation to Your Flutter Application Using MapBox.
  Never leave your app when you need to navigate your users to a location.
version: 0.3.0
homepage: "https://github.com/neildunlop/flutter_mapbox_navigation_2"
repository: "https://github.com/neildunlop/flutter_mapbox_navigation_2"
issue_tracker: "https://github.com/neildunlop/flutter_mapbox_navigation_2/issues"

topics:
  - mapbox
  - navigation
  - maps
  - turn-by-turn
  - gps

environment:
  sdk: '>=2.19.4 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter:
  plugin:
    platforms:
      android:
        package: com.neiladunlop.fluttermapboxnavigation2
        pluginClass: FlutterMapboxNavigationPlugin
      ios:
        pluginClass: FlutterMapboxNavigationPlugin
